### ISSUE TITLE
post location riddles

### ISSUE THREAD

**Issue by flyingbeat** [uzh-ase-fs24/workspace#10]
**As a:** [quizzer](https://github.com/uzh-ase-fs24/whami/wiki/Glossary#quizzers)
**I want:** to post [location riddles](https://github.com/uzh-ase-fs24/whami/wiki/Glossary#location-riddle) to the application
**So that:** my [quizzees](https://github.com/uzh-ase-fs24/whami/wiki/Glossary#quizzees) are able to interact and solve my location riddles

- [x] uzh-ase-fs24/backend#18
- [x] uzh-ase-fs24/backend#24
- [x] uzh-ase-fs24/frontend#16
