### ISSUE TITLE
view location riddles in feed

### ISSUE THREAD

**Issue by flyingbeat** [uzh-ase-fs24/workspace#11]
**As a:** [quizzee](https://github.com/uzh-ase-fs24/whami/wiki/Glossary#quizzees) 
**I want:** to view [location riddles](https://github.com/uzh-ase-fs24/whami/wiki/Glossary#location-riddle) posted by the quizzers I follow
**So that:** I can see and solve all the location riddles posted by the quizzers I follow

- [x] uzh-ase-fs24/backend#39
- [x] uzh-ase-fs24/backend#36
- [x] uzh-ase-fs24/frontend#17
- [x] view to display multiple location components
