### ISSUE TITLE
rate location riddle

### ISSUE THREAD

**Issue by flyingbeat** [uzh-ase-fs24/workspace#15]
**As a:** [quizzee](https://github.com/uzh-ase-fs24/whami/wiki/Glossary#quizzees) 
**I want:** to rate [location riddles](https://github.com/uzh-ase-fs24/whami/wiki/Glossary#location-riddle) I see in my feed
**So that:** I can express my opinion on the quality of the riddle

- [x] uzh-ase-fs24/backend#45
- [x] uzh-ase-fs24/backend#54
- [x] uzh-ase-fs24/frontend#17 functionality to rate a location riddle
- [x] uzh-ase-fs24/frontend#24
