### ISSUE TITLE
receiving score points for solving location riddles

### ISSUE THREAD

**Issue by flyingbeat** [uzh-ase-fs24/workspace#16]
**As a:** [quizzee](https://github.com/uzh-ase-fs24/whami/wiki/Glossary#quizzees)
**I want:** to receive score points for solving a [location riddle](https://github.com/uzh-ase-fs24/whami/wiki/Glossary#location-riddle) according to how precise my guess was
**So that:** I can compete with other quizzers

- [x] uzh-ase-fs24/backend#50
- [x] uzh-ase-fs24/backend#51
- [x] uzh-ase-fs24/backend#57
