### ISSUE TITLE
project setup

### ISSUE THREAD

**Issue by flyingbeat** [uzh-ase-fs24/workspace#27]
**As a:** developer
**I want:** to generate the frontend and backend boilerplate code
**So that:** I have a working development setup with a minimal application (hello world)

## Tasks
- [x] uzh-ase-fs24/frontend#1
- [x] uzh-ase-fs24/backend#1
- [x] uzh-ase-fs24/backend#3
- [x] uzh-ase-fs24/workspace#38
- [x] uzh-ase-fs24/frontend#6
