### ISSUE TITLE
update quizzer profile

### ISSUE THREAD

**Issue by flyingbeat** [uzh-ase-fs24/workspace#6]
**As a:** [quizzer](https://github.com/uzh-ase-fs24/whami/wiki/Glossary#quizzers) 
**I want:** to update my personalized quizzer profile
**So that:** I can interact with the application with my updated custom profile

- [x] uzh-ase-fs24/backend#11
- [x] uzh-ase-fs24/backend#15
- [x] uzh-ase-fs24/frontend#11
