### ISSUE TITLE
search for other quizzers

### ISSUE THREAD

**Issue by flyingbeat** [uzh-ase-fs24/workspace#7]
**As a:** [quizzer](https://github.com/uzh-ase-fs24/whami/wiki/Glossary#quizzers) 
**I want:** to search for other quizzers by their username
**So that:** I can see their profile and follow them

- [x] uzh-ase-fs24/backend#22
- [x] uzh-ase-fs24/backend#25
- [x] uzh-ase-fs24/frontend#14
- [x] uzh-ase-fs24/backend#26
