### ISSUE TITLE
follow other quizzers

### ISSUE THREAD

**Issue by flyingbeat** [uzh-ase-fs24/workspace#8]
**As a:** [quizzer](https://github.com/uzh-ase-fs24/whami/wiki/Glossary#quizzers) 
**I want:** to send a follow request to other quizzers
**So that:** I am able to see and solve their [location riddles](https://github.com/uzh-ase-fs24/whami/wiki/Glossary#location-riddle)

- [x] uzh-ase-fs24/frontend#12
- [x] uzh-ase-fs24/backend#28
- [x] uzh-ase-fs24/backend#29
